name: "🐛 Bug Report"
description: "Report an issue to help us improve Weekend Knocks"
title: "Bug:"
labels: ["bug", "help wanted"]
body:
  - type: checkboxes
    attributes:
      label: "Have you checked for existing issues?"
      description: "Search to ensure the issue hasn't already been reported."
      options:
        - label: "I have searched and found no existing issue."
          required: true
  - type: textarea
    attributes:
      label: "Describe the Bug"
      description: "Provide a clear and concise description of the issue you're experiencing."
      placeholder: "What went wrong?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behavior and Additional Context"
      description: "Describe the expected behavior, and if applicable, attach any relevant screenshots or logs to provide more context."
      placeholder: "Explain what you expected to happen and include additional context like screenshots or logs if necessary."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Acknowledgements"
      description: "Please confirm the following:"
      options:
        - label: "I agree to follow this project's Code of Conduct."
          required: true
        - label: "I'm a SWOC'25 contributor."
        - label: "I have read the contribution guidelines."
        - label: "I want to work on this issue."
