name: "🐛 Bug Report"
description: "Report an issue to help us improve Weekend Knocks"
title: "Bug:"
labels: ["bug", "help wanted"]
body:
  - type: checkboxes
    attributes:
      label: "Have you checked for existing issues?"
      description: "Search to ensure the issue hasn't already been reported."
      options:
        - label: "I have searched and found no existing issue."
          required: true
  - type: textarea
    attributes:
      label: "Describe the Bug"
      description: "Provide a clear and concise description of the issue you're experiencing."
      placeholder: "What went wrong?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "What you expected to happen instead."
      placeholder: "Explain the desired outcome."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots or Logs (if applicable)"
      description: "Attach any relevant screenshots or logs to provide more context."
      placeholder: "Upload or describe here."
  - type: textarea
    attributes:
      label: "Acknowledgements"
      description: "Please confirm the following:"
      options:
        - label: "I agree to follow this project's Code of Conduct."
          required: true
        - label: "I'm a SWOC'24 contributor"
        - label: "I have read the contribution guidelines."
        - label: "I want to work on this issue."
