name: "✨ Feature Request"
description: "Suggest an idea for this project"
title: "Feat:"
labels: ["Feat", "Needs Triage"]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description: "Provide a clear and concise description of the feature you are suggesting."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add Screenshots or Mockups"
      description: "Attach screenshots, diagrams, or mockups to explain your feature better."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Acknowledgements"
      options:
        - label: "I agree to follow this project's Code of Conduct."
          required: true
        - label: "I'm a SWOC'25 contributor."
        - label: "I want to work on this issue."
