name: Auto Label on Issue Creation

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Labels to Issue
        run: |
          # Extract the template used
          TEMPLATE="${{ github.event.issue.body }}"

          # Define the labels based on the template
          if [[ "$TEMPLATE" == *"bug"* ]]; then
            LABELS=("bug" "under-review")
          elif [[ "$TEMPLATE" == *"feature"* ]]; then
            LABELS=("feature" "under-review")
          elif [[ "$TEMPLATE" == *"documentation"* ]]; then
            LABELS=("documentation" "under-review")
          else
            LABELS=("under-review")
          fi

          # Add the labels to the issue
          for LABEL in "${LABELS[@]}"; do
            RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
              -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"labels\":[\"$LABEL\"]}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels)

            # Check if the label was added successfully
            if [ "$RESPONSE" -ne 200 ]; then
              echo "Failed to add label $LABEL"
              exit 1
            fi
          done

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
